/**
 ****************************************************************************************
 *
 * @file 32M/partition_table.h
 *
 * Copyright (C) 2016-2017 Dialog Semiconductor.
 * This computer program includes Confidential, Proprietary Information
 * of Dialog Semiconductor. All Rights Reserved.
 *
 ****************************************************************************************
 */

#define NVMS_PRODUCT_HEADER_PART_START  0x000000
#define NVMS_PRODUCT_HEADER_PART_SIZE   0x002000    //8KB

#define NVMS_FIRMWARE_PART_START        NVMS_PRODUCT_HEADER_PART_START+ NVMS_PRODUCT_HEADER_PART_SIZE
#define NVMS_FIRMWARE_PART_SIZE         0x200000    //2048KB

#define NVMS_PARTITION_TABLE_START      NVMS_FIRMWARE_PART_START + NVMS_FIRMWARE_PART_SIZE
#define NVMS_PARTITION_TABLE_SIZE       0x001000    //4KB

#define NVMS_FW_UPDATE_PART_START       NVMS_PARTITION_TABLE_START + NVMS_PARTITION_TABLE_SIZE
#define NVMS_FW_UPDATE_PART_SIZE        0x200000    //2048KB

#define NVMS_UX_RESOURCE_PART_START     NVMS_FW_UPDATE_PART_START + NVMS_FW_UPDATE_PART_SIZE
#define NVMS_UX_RESOURCE_PART_SIZE      0x18FF000    //25596KB

#define NVMS_RESERVED_PART_START        NVMS_UX_RESOURCE_PART_START + NVMS_UX_RESOURCE_PART_SIZE
#define NVMS_RESERVED_PART_SIZE         0X100000    //1024KB

#define NVMS_WORKOUT_HISTORY_PART_START NVMS_RESERVED_PART_START + NVMS_RESERVED_PART_SIZE
#define NVMS_WORKOUT_HISTORY_PART_SIZE  0x1C0000    //1792KB

#define NVMS_LOG_PART_START             NVMS_WORKOUT_HISTORY_PART_START + NVMS_WORKOUT_HISTORY_PART_SIZE
#define NVMS_LOG_PART_SIZE              0x010000    //64KB

#define NVMS_APP_PARAM_PART_START       NVMS_LOG_PART_START + NVMS_LOG_PART_SIZE
#define NVMS_APP_PARAM_PART_SIZE        0x00A000    //40KB

#define NVMS_GENERIC_PART_START         NVMS_APP_PARAM_PART_START + NVMS_APP_PARAM_PART_SIZE
#define NVMS_GENERIC_PART_SIZE          0x020000    //128KB

#define NVMS_PLATFORM_PARAMS_PART_START NVMS_GENERIC_PART_START + NVMS_GENERIC_PART_SIZE
#define NVMS_PLATFORM_PARAMS_PART_SIZE  0x003000    //12KB

#define NVMS_PARAM_PART_START           NVMS_PLATFORM_PARAMS_PART_START + NVMS_PLATFORM_PARAMS_PART_SIZE
#define NVMS_PARAM_PART_SIZE            0x001000    //4KB

PARTITION2( NVMS_PRODUCT_HEADER_PART   , 0 )
PARTITION2( NVMS_FIRMWARE_PART         , 0 )
PARTITION2( NVMS_PARTITION_TABLE       , PARTITION_FLAG_READ_ONLY )
PARTITION2( NVMS_FW_UPDATE_PART        , 0 )
PARTITION2( NVMS_UX_RESOURCE_PART      , 0 )
PARTITION2( NVMS_RESERVED_PART         , 0 )
PARTITION2( NVMS_WORKOUT_HISTORY_PART  , 0 )
PARTITION2( NVMS_LOG_PART              , 0 )
PARTITION2( NVMS_APP_PARAM_PART        , 0 )
PARTITION2( NVMS_GENERIC_PART          , PARTITION_FLAG_VES )
PARTITION2( NVMS_PLATFORM_PARAMS_PART  , PARTITION_FLAG_READ_ONLY )
PARTITION2( NVMS_PARAM_PART            , 0 )
