/**
 ****************************************************************************************
 *
 * @file custom_config_ram.h
 *
 * @brief Board Support Package. User Configuration file for PSRAM mode.
 *
 *
 ****************************************************************************************
 */
#ifndef CUSTOM_CONFIG_PSRAM_H_
#define CUSTOM_CONFIG_PSRAM_H_


/*************************************************************************************************\
 * PSRAM LayOut
 */

#define CONFIG_PSRAM_BASE					(0x32000000UL) 
#define CONFIG_PSRAM_FB_SIZE				(0x38400)
#define CONFIG_PSRAM_GUI_HEAP_SIZE			(0x59600)
#define CONFIG_PSRAM_GUI_TOTAL_SIZE			(0x91A00)
/*
0x3200_0000 ~ 0x3209_1A00  : For Display buffer
	#define GDI_FRAME_BUFFER_ADDR                   (qspi_automode_addr(dg_configQSPI2_FLASH_BASE_ADDR))
	#define GDI_GUI_HEAP_AREA_ADDR                  (GDI_FRAME_BUFFER_ADDR +             
*/

#define CONFIG_PSRAM_HEAP_BASE				(CONFIG_PSRAM_BASE + CONFIG_PSRAM_GUI_TOTAL_SIZE )
#define CONFIG_PSRAM_HEAP_SIZE				(0x20000)


#define CONFIG_PSRAM_BSS_BASE				(CONFIG_PSRAM_HEAP_BASE + CONFIG_PSRAM_HEAP_SIZE )
#define CONFIG_PSRAM_BSS_SIZE				(0x20000)

#define CONFIG_PSRAM_LOGBACKUP_BUFFER_ADDR	(CONFIG_PSRAM_BSS_BASE + CONFIG_PSRAM_BSS_SIZE )
#define CONFIG_PSRAM_LOGBACKUP_BUFFER_SIZE	(0x10000)

#define CONFIG_PSRAM_POWER_DUMP_ADDR		(CONFIG_PSRAM_LOGBACKUP_BUFFER_ADDR	+ CONFIG_PSRAM_LOGBACKUP_BUFFER_SIZE )
#define CONFIG_PSRAM_POWER_DUMP_SIZE		(0xB000)

#define CONFIG_PSRAM_LOG_BUFFER_ADDR		(CONFIG_PSRAM_POWER_DUMP_ADDR + CONFIG_PSRAM_POWER_DUMP_SIZE )
#define CONFIG_PSRAM_LOG_BUFFER_SIZE		(0x10000)

#define CONFIG_PSRAM_ASSERTLOG_BUFFER_ADDR	(CONFIG_PSRAM_LOG_BUFFER_ADDR + CONFIG_PSRAM_LOG_BUFFER_SIZE )
#define CONFIG_PSRAM_ASSERTLOG_BUFFER_SIZE	(0x1000)

#define CONFIG_PSRAM_GDI_BACKUP_ADDR		(CONFIG_PSRAM_ASSERTLOG_BUFFER_ADDR + CONFIG_PSRAM_ASSERTLOG_BUFFER_SIZE )
#define CONFIG_PSRAM_GDI_BACKUP_SIZE		(CONFIG_PSRAM_GUI_HEAP_SIZE)

//#define CONFIG_PSRAM_HEAP_BACKUP_ADDR		(CONFIG_PSRAM_GDI_BACKUP_ADDR + CONFIG_PSRAM_GDI_BACKUP_SIZE)
//#define CONFIG_PSRAM_HEAP_BACKUP_SIZE		(CONFIG_PSRAM_HEAP_SIZE)
#define CONFIG_PSRAM_BSS_BACKUP_ADDR		(CONFIG_PSRAM_GDI_BACKUP_ADDR + CONFIG_PSRAM_GDI_BACKUP_SIZE)
#define CONFIG_PSRAM_BSS_BACKUP_SIZE		(CONFIG_PSRAM_BSS_SIZE)


#define CONFIG_PSRAM_DUMP_BASE                  (CONFIG_PSRAM_BASE + CONFIG_PSRAM_FB_SIZE )
#define CONFIG_PSRAM_DUMP_SIZE                  (CONFIG_PSRAM_GDI_BACKUP_SIZE)

#define CONFIG_PSRAM_BOOTINFO_ADDR			(0x3217E000UL)
#define CONFIG_PSRAM_BOOTINFO_SIZE			(0x2000)

#define CONFIG_PSRAM_IRAM_BACKUP_ADDR		(0x32180000UL)
#define CONFIG_PSRAM_IRAM_BACKUP_SIZE		(0x80000)
/*
0x3217_0000 ~ 0x3220_0000  : For RAM DUMP
	0x3217_E000	~ 0x3217_E010	INFORM				0x10		16B		INFORM data
	0x3217_E510	~ 0x3217_E5C0	FAULT_header_addr	0xB0		156B	FAULT_header_addr
	0x3217_E5C0	~ 0x3218_0000	FAULT_regs_addr		0x1A40		6720B	FAULT_regs_addr
	0x3218_0000	~ 0x3220_0000	FAULT_ram_addr		0x80000		512KB	FAULT_ram_addr
*/

#endif /* CUSTOM_CONFIG_PSRAM_H_ */
