#define SW_VERSION "R370XXU0ARL1"
#define RSRC_VERSION "R370XXU0ARL1"
#define SW_VERSION_DATE "2018-12-06 17:00"
#define SW_VERSION_STATUS "REPOSITORY VERSION"
#define MODEL_NAME "Galaxy Fit"
#define MODEL_NUMBER "SM-R370"
#define MAIN_CHIP "DA14697"
#define BINARY_TYPE          USER_BINARY
#define dg_configIMAGE_SETUP DEVELOPMENT_MODE
