#define BLACKORCA_SW_VERSION "1.0.0.1"
#define BLACKORCA_SW_VERSION_DATE "2018-02-15 15:00 "
#define BLACKORCA_SW_VERSION_STATUS "REPOSITORY VERSION"
#define BLACKORCA_MAIN_CHIP "DA14697"
#define BINARY_TYPE          USER_BINARY
#define dg_configIMAGE_SETUP DEVELOPMENT_MODE
#define dg_configDEVICE DEVICE_D2522
